### ISSUE TITLE
Problem Executing WebService Example

### ISSUE THREAD

**Issue by fpozoc** [appris/appris#18]
Hi José, 

I got the following problem when I tried to execute the example command line order. How can I fix it in order to run Appris by terminal properly?
```
XXXX@XXXX:~/Desktop$ perl appris_runner.pl -s human -g ENSG00000099904 -a hg19 -o ENSG00000099904.out -m firestar,spade -f gtf
[rest_request] Begin
[rest_user_agent] Begin
[rest_user_agent] End
[rest_error] Begin
[rest_error] End
[rest_request] End
[rest_request] Begin
[rest_user_agent] Begin
[rest_user_agent] End
[rest_error] Begin
[rest_error] End
[rest_request] End
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at appris_runner.pl line 113.
```

**Comment by Amanda2018genetics** [comment]
Hi fpozoc,
I have the same error when running the command in my terminal, Did you get  the reason and  solve  the problem?
Yao

**Comment by appris** [comment]
Hi Yao (and Fernando),

We have fixed the bug in the client scripts.
Check the new commit.

Sorry for the inconvenience caused,
APPRIS team
