### ISSUE TITLE
Can't access to the http://appris.bioinfo.cnio.es/

### ISSUE THREAD

**Issue by rstatistics** [appris/appris#19]
sorry to report that we couldn't visit http://appris.bioinfo.cnio.es/, and the webpage returns: "Server92-unavailable!".

**Comment by tdido** [comment]
Thank you for reporting this. There was some scheduled downtime during the weekend for electrical works. It should be up and running now.

**Comment by rstatistics** [comment]
Thank you very much! I can visit the webpage now!

**Comment by tdido** [comment]
Great. Thanks again for reporting.
